spring.application.name=autotrack-springboot

spring.datasource.url=jdbc:mysql://localhost:3307/freelance_tracker?serverTimezone=UTC
spring.datasource.username=graciafernandez
spring.datasource.password=iesarrabalMG15.@

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false