spring.application.name=autotrack-springboot
spring.config.import=optional:file:.env

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false